version: "2"
run:
  tests: true
linters:
  enable:
    - gosec
    - lll
    - misspell
    - nakedret
    - unconvert
    - unparam
  disable:
    - depguard
    - dupl
    - goconst
    - gocyclo
    - prealloc
    - staticcheck
    - unused
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    govet:
      disable:
        - shadow
    misspell:
      locale: UK
      ignore-rules:
        - statuser
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        source: github.com/utilitywarehouse/ordering-platform
      - path: (.+)\.go$
        text: Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv|.*Disconnect). is not checked
      - path: (.+)\.go$
        text: exported var \w+ should have comment or be unexported
      - path: (.+)\.go$
        text: func name will be used as test\.Test.* by other packages, and that stutters; consider calling this
      - path: (.+)\.go$
        text: Use of unsafe calls should be audited
      - path: (.+)\.go$
        text: Subprocess launch(ed with variable|ing should be audited)
      - path: (.+)\.go$
        text: G104
      - path: (.+)\.go$
        text: (Expect directory permissions to be 0750 or less|Expect file permissions to be 0600 or less)
      - path: (.+)\.go$
        text: Potential file inclusion via variable
      - path: (.+)\.go$
        text: (possible misuse of unsafe.Pointer|should have signature)
      - path: (.+)\.go$
        text: ineffective break statement. Did you mean to break out of the outer loop
      - path: (.+)\.go$
        text: exported [a-z]+ `?[^ ]+ should have comment
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - generated$
